name: wayshub-backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  init:

    runs-on: ubuntu-latest 
    environment: wayshub

    steps:
    - name: checkout scm
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build -t millinovz/wayshub-${{ vars.TAG }}:v1 .

    - name: Docker Login
      uses: docker/login-action@v4.6.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Push
      run: docker push millinovz/wayshub-${{ vars.TAG }}:v1
  
  test:
    runs-on: ubuntu-latest
    environment: wayshub
    needs: init

    steps:
    - name: Execute SSH for deployment
      uses: appleboy/ssh-action@v1.2.5
      with:
          host: ${{ secrets.BUILD_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd project/wayshub-${{ vars.TAG }}
            docker pull millinovz/wayshub-${{ vars.TAG }}:v1
            docker run -d --rm --name test-backend -p 5000:5000 millinovz/wayshub-${{ vars.TAG }}:v1
            sleep 10
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST http://localhost:5000/api/v1/login \
            -H "Content-Type: application/json" \
            -d '{"email":"test@test.com","password":"test"}')
            echo "Status: "
            echo $STATUS
            docker stop test-backend
            if [ "$STATUS" != "200" ]; then
              echo "Build has failed the test"
              exit 1
            fi
            echo "Build has run successfully!"

  deploy:
    runs-on: ubuntu-latest
    environment: wayshub
    needs: test

    steps:
    - name: Execute SSH for deployment
      uses: appleboy/ssh-action@v1.2.5
      timeout-minutes: 15
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd docker/
            docker compose pull
            docker compose down
            docker compose up -d
    - name: Discord Webhook
      uses: tsickert/discord-webhook@v7.0.0  
      with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: millinov-webhook-backend
          avatar-url: https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024
          embed-title: "Millinov has successfully run GitHub Action and use Discord Webhook for Backend Repo"
          embed-url: "https://youtu.be/cvj0RvSQnr4?si=W_ugSOZU7glJdW62"
          embed-description: "Saya sudah mencoba lagi menggunakan github action untuk melakukan discord hook, jika message ini terlihat berarti sudah berjalan dengan baik"
          embed-author-name: "Millinov"
          embed-author-url: "https://github.com/millinov"
          embed-author-icon-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-thumbnail-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-image-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-color: 15430476

  notif:
    runs-on: ubuntu-latest
    environment: wayshub

    steps:
    - name: Discord Webhook send success notification
      if: ${{ success() }}
      uses: tsickert/discord-webhook@v7.0.0  
      with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: millinov-webhook-backend
          avatar-url: https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024
          embed-title: "Millinov has successfully deploy Wayshub Backend"
          embed-url: "https://youtu.be/cvj0RvSQnr4?si=W_ugSOZU7glJdW62"
          embed-description: "Saya sudah mencoba lagi menggunakan github action untuk melakukan discord hook, jika message ini terlihat berarti sudah berjalan dengan baik"
          embed-author-name: "Millinov"
          embed-author-url: "https://github.com/millinov"
          embed-author-icon-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-thumbnail-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-image-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-color: 1565507
    - name: Discord Webhook send failure notification
      if: ${{ failure() }}
      uses: tsickert/discord-webhook@v7.0.0  
      with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: millinov-webhook-backend
          avatar-url: https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024
          embed-title: "Millinov has failed to deploy Wayshub Backend"
          embed-url: "https://youtu.be/cvj0RvSQnr4?si=W_ugSOZU7glJdW62"
          embed-description: "Saya sudah mencoba lagi menggunakan github action untuk melakukan discord hook, jika message ini terlihat berarti sudah berjalan dengan baik"
          embed-author-name: "Millinov"
          embed-author-url: "https://github.com/millinov"
          embed-author-icon-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-thumbnail-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-image-url: "https://cdn.discordapp.com/avatars/325643144236367873/ec0a9440f1e3f7e5ff8a39be456d813f.png?size=1024"
          embed-color: 16515876




